nelmio_api_doc:
    name:                   API documentation AAID
    sandbox:
        enabled:            true
        endpoint:           http://localhost/apps/aaid/web/app_dev.php
        authentication:
            name: X-Auth-Token
            delivery: header

        accept_type: application/json   # valeur par défaut de l'entête Accept

        body_format:
            formats: [ json, xml ]                                 
            default_format: json                

        request_format:
            formats:                           
                json: application/json         
                xml: application/xml           

            method: accept_header     
            default_format: json
    cache:
        enabled:            false
        file:               '%kernel.cache_dir%/api-doc.cache'
