<?php

namespace Member\MemberBundle\Repository;

/**
 * Sys_TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sys_TransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
