<?php

namespace Member\MemberBundle\Repository;

/**
 * Sys_HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sys_HistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
