<?php

namespace ParamAdmin\ParamAdminBundle\Repository;

/**
 * Param_ContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Param_ContributionRepository extends \Doctrine\ORM\EntityRepository
{
}
