<?php

namespace ParamAdmin\ParamAdminBundle\Repository;

/**
 * Param__ContributionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Param_ContributionsRepository extends \Doctrine\ORM\EntityRepository
{
}
