<?php

namespace ParamAdmin\ParamAdminBundle\Repository;

/**
 * Param_OfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Param_OfficeRepository extends \Doctrine\ORM\EntityRepository
{
}
