<?php

namespace ParamAdmin\ParamAdminBundle\Repository;

/**
 * Sys_SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sys_SessionRepository extends \Doctrine\ORM\EntityRepository
{
}
