<?php

namespace ParamAdmin\ParamAdminBundle\Repository;

/**
 * Sys_AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SysAssociationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAssociations($offset, $limit, $sort) {
        $req = $this->createQueryBuilder('a')
                ->where("a.isDelete = 0")
                ;
        
        if ($offset != "") {
            $req->setFirstResult($offset);
        }

        if ($limit != "") {
            $req->setMaxResults($limit);
        }
        
        if (in_array($sort, ['asc', 'desc'])) {
            $req->orderBy('a.createdAt', $sort);
        }
        
        return $req->getQuery()->getResult();
    }
    
    public function findInscription($assoc, $session) {
        $req = $this->createQueryBuilder('a')
                ->leftJoin('a.inscriptions', 'i')
                ->leftJoin('i.sessions', 's')
//                ->where("a.inscriptions = " . $assoc)
                ->andWhere('i.sessions = '.$session)
            ;
    }
}
