<?php

namespace ParamAdmin\ParamAdminBundle\Repository;

/**
 * SysSessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SysSessionsRepository extends \Doctrine\ORM\EntityRepository
{
}
